---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snap-report-backend-deployment
  labels:
    app: snap-report-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snap-report-backend-app
  template:
    metadata:
      labels:
        app: snap-report-backend-app
    spec:
      nodeSelector:
        nodepool: infrastructure
      containers:
      - name: snap-report-backend-app-deployment
        image: docker-hosted.snap-ci.ovh/snap-reports-backend:latest
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: "100m"
        ports:
        - containerPort: 9090
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snap-report-backend-mysql-connection
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: snap-report-backend-mysql-connection
              key:  MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: snap-report-backend-mysql-connection
              key:  MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: snap-report-backend-mysql-connection
              key:  MYSQL_USER